package top.qianxinyao.model;

import top.qianxinyao.model.base.BaseNewsadded;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newsadded extends BaseNewsadded<Newsadded> {
	public static final Newsadded dao = new Newsadded().dao();
}
